# application mode. Choices are console, udp, tcp
modes = ["console", "tcp", "udp"]
# script file location
scriptdir = "/etc/logtrics/scripts/"

# single script file. Useful for debugging
#scriptfile = "examples/demo.lua"

# buffer size of log event channel
# buffersize = 0

# graphite server configuration
[graphite]
  debug = false
  host = "127.0.0.1"
  interval = 30
  port = 2024

# logging configuration
[logging]
  # level of logging. Choices are fatal, error, warn, info, debug, trace
  level = "info"
  # type of logging. Choices are console, syslog
  type = "console"

# TCP serve mode
[tcp]
  host = "127.0.0.1"
  port = 4003

# UDP listener mode
[udp]
  host = "127.0.0.1"
  port = 4002
